ALTER TABLE ozel_ders_icerikleri RENAME TO ders_icerikleri;
ALTER TABLE ders_icerikleri ADD COLUMN baglantiSlotId INTEGER;

CREATE TABLE ders_kullanim_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dersId TEXT NOT NULL,
  tarih TEXT NOT NULL,
  kullanan TEXT,
  t INTEGER NOT NULL
);
CREATE INDEX idx_ders_kullanim_dersid ON ders_kullanim_log(dersId);

CREATE TABLE ders_degerlendirme (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dersId TEXT NOT NULL,
  puan INTEGER NOT NULL,
  degerlendiren TEXT,
  t INTEGER NOT NULL
);
CREATE INDEX idx_ders_degerlendirme_dersid ON ders_degerlendirme(dersId);

INSERT INTO ders_icerikleri (id, tip, baslik, seviye, gruplar_json, sure, malzeme, aciklama, adimlar_json, dikkat_json, olusturan, olusturulma, guncelleme) VALUES
('teknik-01', 'teknik', 'Duruş ve Ayak Pozisyonu Temelleri', 'baslangic', '["buyukler","yildizlar","kucukler","minikler"]', 30, 'Hedef, işaret bandı, klasik/makaralı yaylar', 'Okçuluğun temel taşı olan duruşu ve ayak pozisyonunu (paralel, açık, kapalı duruş) doğru oturtmaya odaklanan bir ders.', '["5dk ısınma ve kol/omuz germe hareketleri","Atış hattına paralel duruşu bant ile işaretleyip her sporcuya kendi ayak izini buldurma","Yaysız, sadece duruş ve gövde dikliği tekrarı (10 tekrar)","Yayla birlikte 3-4 seri deneme atışı, her seride duruş kontrolü","Kapanış: en iyi duruşu sergileyen 2-3 sporcuyu örnek gösterme"]', '["Ağırlık iki ayağa eşit dağılmalı, öne/arkaya yaslanma olmamalı","Omuzlar atış hattına paralel, gövde gereksiz burkulmamalı","Dizler kilitli değil, hafif esnek olmalı"]', 'Sistem', 1784413500670, 1784413500670),
('teknik-02', 'teknik', 'Ok Yerleştirme (Nocking) ve Yay Tutuşu', 'baslangic', '["buyukler","yildizlar","kucukler","minikler"]', 25, 'Ok, yay, nock göstergesi', 'Oku ipe doğru ve güvenli şekilde takma, yay kolunu gevşek ve doğru kavrama alışkanlığı kazandırma.', '["Nock noktasının ok üzerindeki yerini gösterme ve \"klik\" sesini tanıtma","Her sporcuyla tek tek yavaş nocking tekrarı (5 tekrar)","Yay tutuşunu (gevşek, \"tokalaşır gibi değil, dayar gibi\") anlatma ve kontrol","Nocking + tutuş birleşik 10 kuru çekiş (ok atmadan)","3 seri gerçek atışla pekiştirme"]', '["Ok her zaman iplikten SONRA yerleştirilir, asla ok takılıyken yay gerilmez","Yay kolu sıkı kavranırsa \"el sıçraması\" (torque) oluşur, bilek gevşek kalmalı","Nock sesi duyulmadan atış yapılmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('teknik-03', 'teknik', 'Çekiş Tekniği ve Sırt Kaslarının Kullanımı', 'orta', '["buyukler","yildizlar"]', 35, 'Lastik çekiş bandı, yay', 'Çekişi kol kasıyla değil sırt/kürek kemiği kaslarıyla yapma alışkanlığını lastik bant çalışmalarıyla kazandırır.', '["Lastik bant ile 15 tekrar \"kürek kemiklerini birbirine yaklaştırma\" hareketi","Aynayla ya da eş kontrolüyle omuz hizası gözlemi","Yaysız çekiş simülasyonu (10 tekrar)","Gerçek yayla 4 seri, her serinin sonunda geri bildirim","Yorgunluk belirtisi (kol titremesi) gözlenirse mola"]', '["Çekiş kolundaki dirsek omuz hizasında ya da hafif üstünde olmalı","Boyun/trapez kasları gerilmemeli, gevşek kalmalı","Erken yorulma varsa seri sayısını azalt, teknik bozulmasın"]', 'Sistem', 1784413500670, 1784413500670),
('teknik-04', 'teknik', 'Çene Referans Noktası (Anchor Point) Oturtma', 'baslangic', '["buyukler","yildizlar","kucukler"]', 25, 'Yay, ok, ayna (opsiyonel)', 'Her atışta parmakların/ipin yüze aynı noktada değmesini sağlayarak tutarlılık kazandırır.', '["Sporcunun kendi anatomisine uygun referans noktasını (çene altı, ağız kenarı vb.) belirleme","Aynı noktaya 10 kuru çekişle dokunma alıştırması","Gözler kapalı, sadece dokunma hissiyle referans bulma denemesi","3 seri gerçek atış, her okta referans noktasını sesli kontrol ettirme"]', '["Referans noktası seriden seriye KAYMAMALI — tutarlılık puan istikrarının anahtarı","Baş öne eğilmemeli, referans noktası ele/ipe gelmeli, baş ona gitmemeli"]', 'Sistem', 1784413500670, 1784413500670),
('teknik-05', 'teknik', 'Nişan Alma Temelleri (Sight Kullanımı)', 'orta', '["buyukler","yildizlar"]', 30, 'Sight aparatlı yay, hedef', 'Sight noktasının hedef üzerinde sabit tutulması ve "salınım" (float) ile başa çıkma tekniklerini öğretir.', '["Sight ayarının mesafeye göre nasıl değiştiğini gösterme","Nokta sabitleme alıştırması (nefes tutmadan, doğal salınımı kabul ederek)","5 ok deneme atışı, sight noktası gözlem notu tutma","Sight ayarını mesafeye göre yeniden kalibre etme","2 seri kontrol atışı"]', '["Mükemmel sabitlik beklenmemeli — küçük salınım normaldir, zorlamak formu bozar","Sight ayarı değiştirmeden önce en az 3-4 ok ile doğrulama yapılmalı"]', 'Sistem', 1784413500670, 1784413500670),
('teknik-06', 'teknik', 'Salıverme (Release) ve Takip Hareketi (Follow-through)', 'orta', '["buyukler","yildizlar","kucukler"]', 30, 'Yay, lastik çekiş bandı', 'Parmakların/serbest bırakma mekanizmasının ani değil "gevşeyerek" açılmasını ve atış sonrası duruşun korunmasını öğretir.', '["Lastik bantla yavaş salıverme tekrarı (10x)","\"Salıverdikten sonra 2 saniye pozisyonda kal\" kuralını uygulama","4 seri gerçek atış, her okta takip hareketi gözlemi","Video/gözlemci geri bildirimiyle düzeltme turu"]', '["Salıverme elle \"açma\" değil, kasların gevşemesiyle olmalı","Atıştan hemen sonra eli indirmek form bozukluğuna işaret eder","Çekiş eli atıştan sonra omuz/boyun hizasında kalmalı"]', 'Sistem', 1784413500670, 1784413500670),
('teknik-07', 'teknik', '3 Metre Teknik Atış — Temel Form Kontrolü', 'baslangic', '["kucukler","minikler","yildizlar"]', 30, 'Hedef kağıdı, 3m işaretleme', 'Kısa mesafede isabetten çok FORM doğruluğuna odaklanan, yeni başlayanlar için ideal kontrol dersi.', '["3m mesafeyi işaretleyip herkesi sıraya dizme","Her sporcunun 3 oku, aralarda duruş/anchor/salıverme kontrolüyle atılması","Eğitmen her sporcuda TEK bir teknik noktaya odaklanıp anında geri bildirim verir","Tekrar 3 ok, düzeltmenin uygulanıp uygulanmadığını gözlemleme"]', '["Bu derste amaç isabet değil form — puan üzerinden baskı kurulmamalı","Her sporcuya en fazla 1-2 düzeltme notu verilmeli, bilgi kirliliği yaratılmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('teknik-08', 'teknik', '5 Metre Teknik Atış — Nişan İstikrarı ve Tekrarlanabilirlik', 'orta', '["buyukler","yildizlar"]', 35, 'Hedef, 5m işaretleme, skor kağıdı', 'Mesafe arttıkça bozulan formu 5m üzerinden test edip seri içi tutarlılığı geliştirir.', '["5m mesafede 6 oktan oluşan 3 seri attırma","Her serinin ok dağılımını (grup halinde mi, dağınık mı) not etme","Dağınıklık varsa duruş/anchor kontrolü yapıp tekrar deneme","Son seri karşılaştırmalı değerlendirme"]', '["Ok grubu dağınıksa önce EKİPMANI değil TEKNİĞİ kontrol et","Rüzgarlı/gölgeli kapalı alan farkı yoksa dış etken aranmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('teknik-09', 'teknik', 'Nefes Kontrolü ve Atış Ritmi', 'orta', '["buyukler","yildizlar","kucukler"]', 25, 'Yay, kronometre (opsiyonel)', 'Her atışta aynı nefes ve zamanlama düzenini kurarak tutarlılığı artırır.', '["Nefes alma-çekiş-tutma-salıverme sırasını sözlü anlatma","Yaysız 5 tekrar nefes+hareket senkronizasyonu","Yayla 3 seri, her okta aynı ritmi uygulama denemesi","Acele eden sporculara \"sayarak atış\" tekniği önerme"]', '["Nefes tutma çok uzun sürerse gerginlik/titreme artar, 3-4 saniyeyi geçmemeli","Her sporcunun kendi doğal ritmi olabilir, tek bir kalıp herkese zorlanmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('teknik-10', 'teknik', 'Ekipman Kontrolü ve Atış Alanı Güvenliği', 'baslangic', '["buyukler","yildizlar","kucukler","minikler"]', 20, 'Tüm kulüp ekipmanı', 'Sezon başı veya yeni gruplar için ekipman bakımı ve temel güvenlik kurallarını pekiştiren teorik+uygulamalı ders.', '["İp, tüy, ok ucu kontrolü nasıl yapılır — gösterim","Yay germe/bırakma güvenli prosedürü","Atış hattı ve çekme hattı komutlarını (Atışa Hazır Ol / Çek / Dur) tatbik etme","Ok toplama sırasını (herkes hattı geçmeden önce izin bekler) uygulamalı gösterme"]', '["Boş yay (oksuz) ASLA gerilip bırakılmaz — yaya zarar verir","\"Dur\" komutunda herkes anında atışı keser, bu kural istisnasızdır","Ok toplarken önce görsel/sesli izin alınmalı"]', 'Sistem', 1784413500670, 1784413500670),
('teknik-11', 'teknik', 'Sık Yapılan Teknik Hataların Analizi ve Düzeltilmesi', 'ileri', '["buyukler","yildizlar"]', 35, 'Hedef, varsa video kayıt imkanı', 'Sporcunun kendi atış geçmişindeki tekrar eden hataları (sol/sağ sapma, düşük/yüksek atış) birlikte analiz edip düzeltme planı çıkarır.', '["Sporcunun son serilerindeki ok dağılım eğilimini birlikte inceleme","Yaygın nedenleri (erken salıverme, dirsek düşüklüğü, nişan aceleciliği) eşleştirme","Hedeflenen düzeltme için 3 seri kontrollü atış","Sonuçları karşılaştırıp basit bir \"bir sonraki derse kadar odaklan\" notu bırakma"]', '["Aynı anda birden fazla hata düzeltilmeye çalışılmamalı","Düzeltme sonrası kısa vadede skor düşebilir, bu normal karşılanmalı ve sporcuya açıklanmalı"]', 'Sistem', 1784413500670, 1784413500670),
('eglence-01', 'eglence', 'Balon Patlatma Yarışması', 'baslangic', '["kucukler","minikler","yildizlar"]', 25, 'Balonlar, hedef panosu, iğneli/sivri ok ucu (güvenli)', 'Hedefe balonlar yerleştirilir, isabetli atışla balon patlatmak hem eğlenceli hem motive edici bir tekrar pratiğidir.', '["Hedefe farklı renklerde 5-6 balon yerleştirme","Her sporcuya sırayla 3 ok hakkı tanıma","Patlatılan balon sayısına göre basit bir sıralama tutma","İsteyen sporculara ikinci tur hakkı verme"]', '["Balon patlaması sesi bazı küçük sporcuları ürkütebilir, önceden uyarı yapılmalı","Rekabet coşkusu güvenlik kurallarını (sırayla atış) gölgelememeli"]', 'Sistem', 1784413500670, 1784413500670),
('eglence-02', 'eglence', 'Renkli Hedef Bingo', 'baslangic', '["kucukler","minikler"]', 25, 'Renkli kartlar/bingo kağıdı, standart hedef', 'Sporcuların vurduğu halka renkleri bingo kartındaki kutuları doldurur, ilk kartını tamamlayan kazanır.', '["Her sporcuya 3x3 renkli bingo kartı dağıtma","Vurulan halka rengine karşılık gelen kutuyu işaretletme","Sıra ile devam ederek ilk bingo yapanı belirleme","Bingo yapan sporcuya küçük bir alkış/ödül töreni"]', '["Kart doldurma heyecanı ile aceleci atış yapılmamalı, sıra düzeni korunmalı"]', 'Sistem', 1784413500670, 1784413500670),
('eglence-03', 'eglence', 'Takımlar Arası Puan Yarışı', 'orta', '["buyukler","yildizlar","kucukler"]', 35, 'Hedef, skor tahtası', 'Sporcular 2-3 takıma ayrılır, takım toplam puanına göre yarışılır — bireysel baskıyı azaltıp takım ruhu kazandırır.', '["Dengeli takımlar oluşturma (seviyeye göre karıştırma)","Her takımdan sırayla 1 seri atış, toplam puanı tahtaya yazma","3-4 tur sonunda en yüksek toplamı yapan takımı ilan etme","Kısa bir \"en çok gelişen sporcu\" özel takdiri"]', '["Takım arkadaşını eleştirme değil destekleme kültürü teşvik edilmeli"]', 'Sistem', 1784413500670, 1784413500670),
('eglence-04', 'eglence', 'Sürpriz Hedef (Mystery Target)', 'baslangic', '["kucukler","minikler","yildizlar"]', 20, 'Kapatılmış/örtülü hedef, farklı temalı hedef kağıtları', 'Hedef atış anına kadar örtülü tutulur, ok vurdukça altındaki resim/tema yavaşça ortaya çıkar.', '["Hedefi ilginç bir görselle (hayvan, karakter vb.) kaplama","Sporculara sırayla 2''şer ok attırma","Her turda görselin ne kadar ortaya çıktığını birlikte tahmin etme","Görsel tamamen açığa çıkınca küçük bir kutlama"]', '["Görsel seçimi tüm yaş grubuna uygun ve tarafsız olmalı"]', 'Sistem', 1784413500670, 1784413500670),
('eglence-05', 'eglence', 'Ok Sayısı Azalt (Eleme Usulü Yarışma)', 'orta', '["buyukler","yildizlar"]', 30, 'Hedef, skor kağıdı', 'Her turda en düşük puanı alan sporcu bir sonraki tura daha az ok hakkıyla devam eder, gerilim ve odaklanma artar.', '["1. tur: herkese 3 ok, en düşük puanlı belirleme","2. tur: en düşük puanlı(lar) 2 ok, diğerleri 3 ok ile devam","Final turunda kalan sporcularla şampiyonu belirleme"]', '["\"Elenen\" ifadesi yerine \"yeniden deneme hakkı\" gibi pozitif dil kullanılmalı, moral bozulmasın"]', 'Sistem', 1784413500670, 1784413500670),
('eglence-06', 'eglence', 'Değişken Mesafe Yarışı', 'orta', '["buyukler","yildizlar","kucukler"]', 30, 'Hedef, farklı mesafe işaretleri', 'Her seri farklı bir mesafeden atılır, sporcular hızlı adaptasyon becerisini eğlenceli şekilde geliştirir.', '["3 farklı mesafe belirleme (ör. 5m-8m-10m)","Her mesafeden 1 seri (3-6 ok) attırma","Mesafe bazlı en iyi performansı not etme","Genel toplam üzerinden sıralama açıklama"]', '["Mesafe değişince sight/nişan ayarı hatırlatılmalı, unutulursa büyük sapmalar normal karşılanmalı"]', 'Sistem', 1784413500670, 1784413500670),
('eglence-07', 'eglence', 'Tema Günü — Karakterini Seç', 'baslangic', '["kucukler","minikler","yildizlar"]', 35, 'Temalı hedef kağıtları, basit kostüm aksesuarları (opsiyonel)', 'Süper kahraman, orman kahramanı gibi bir tema etrafında kurgulanan, hikaye anlatımıyla motivasyonu artıran ders.', '["Basit bir hikaye anlatımıyla dersi açma (\"Bugün ormanın koruyucularıyız...\")","Tema ile ilişkili hedeflere atış yaptırma","Her başarılı atışta hikayeyi bir adım ilerletme","Dersi hikayenin \"mutlu sonuyla\" bitirme"]', '["Hikaye kısa ve basit tutulmalı, atış süresinden çalmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('eglence-08', 'eglence', 'Zamana Karşı Yarış', 'orta', '["buyukler","yildizlar"]', 25, 'Hedef, kronometre', 'Belirli sürede en çok isabetli ok atma hedefiyle hız ve odaklanmayı birlikte test eder.', '["2 dakikalık süre belirleme","Sporcu süresince elinden geldiğince (güvenli hızda) ok atar","İsabetli ok sayısını not etme","En iyi 3 performansı duyurma"]', '["Hız için TEKNİK feda edilmemeli, aceleyle güvenlik kuralları çiğnenmemeli"]', 'Sistem', 1784413500670, 1784413500670),
('eglence-09', 'eglence', 'Karışık Takım Bayrak Yarışı', 'baslangic', '["kucukler","minikler","yildizlar"]', 30, 'Hedef, bayrak/işaret nesnesi', 'Takım halinde sırayla atıp koşarak bayrak taşıyan, hem fiziksel hem okçuluk becerisini birleştiren enerjik oyun.', '["Takımları oluşturma ve sıralama belirleme","Her sporcu 1 ok atar, isabet olursa takım bayrağı bir adım ilerler","İlk bitiren takım kazanır","Kısa dinlenme sonrası revanş turu"]', '["Koşu kısmı düz ve güvenli bir zeminde olmalı, atış hattına karışmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('eglence-10', 'eglence', 'Mini Turnuva Simülasyonu', 'ileri', '["buyukler","yildizlar"]', 40, 'Hedef, skor kağıdı, varsa madalya/rozet', 'Gerçek bir turnuva atmosferini (sıra, sessizlik, resmi skor tutma) küçük ölçekte yaşatan hazırlık dersi.', '["Gerçek turnuva kurallarıyla (sırayla atış, sessizlik, resmi skor kağıdı) 3 seri attırma","Skorları resmi şekilde toplayıp sıralama ilan etme","İlk 3''e küçük bir tören yapma","Turnuva deneyimi üzerine kısa bir sohbet/geri bildirim turu"]', '["Gerçek turnuva stresini biraz hissettirmek amaçlı olsa da ders eğlenceli havada bitirilmeli"]', 'Sistem', 1784413500670, 1784413500670),
('oyun-01', 'oyun', 'Ormandan Çıkış Oyunu', 'baslangic', '["kucukler","minikler"]', 35, 'Orman temalı hedef istasyonları, basit haritalar', 'Sporcular "ormanda kaybolmuş" kurgusuyla sırayla istasyonlardaki hedefleri vurarak çıkış yolunu bulur — her doğru vuruş haritada bir adım ilerletir.', '["Basit bir orman haritası çizip 4-5 istasyon belirleme","Hikayeyi anlatarak dersi başlatma","Her istasyonda 2 ok atma hakkı, isabet olursa haritada ilerleme","Son istasyona (çıkışa) ulaşan sporcuları \"orman kaşifi\" ilan etme"]', '["İstasyonlar arası geçişte atış hattı kuralına uyulmalı, koşarak geçilmemeli"]', 'Sistem', 1784413500670, 1784413500670),
('oyun-02', 'oyun', 'Hazine Avı Okçuluğu', 'baslangic', '["kucukler","minikler"]', 30, 'Hazine sandığı görseli/kutusu, ipuçlu kartlar, hedef', 'Her isabetli atışta bir ipucu kartı kazanılır, ipuçları birleştirilince "hazine" bulunur.', '["5 ipucu kartı hazırlayıp hedefin arkasına gizleme","Her isabetli atışta bir ipucu kartı verme","Toplanan ipuçlarıyla basit bir bilmece/harita çözme","Hazineyi (küçük bir ödül/rozet) birlikte bulma"]', '["İpuçları yaş grubuna uygun basitlikte olmalı, oyun uzun sürmemeli"]', 'Sistem', 1784413500670, 1784413500670),
('oyun-03', 'oyun', 'Renk Merdiveni', 'baslangic', '["kucukler","minikler"]', 25, 'Renkli halkalı hedef', 'Sporcu sırasıyla en dıştan en içe (ör. mavi→kırmızı→sarı) doğru vurmayı başarırsa "merdiveni" tırmanmış sayılır.', '["Hedef halkalarını renk sırasıyla tanıtma","Her sporcu dıştan içe doğru sırayla vurmaya çalışır","Bir rengi ıskalarsa o basamakta tekrar dener","Tüm merdiveni tamamlayanları pano üzerinde işaretleme"]', '["Zorlanan sporcular için basamak atlamasına izin verilebilir, oyun cezalandırıcı olmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('oyun-04', 'oyun', 'Uzay Yolculuğu', 'baslangic', '["kucukler","minikler"]', 30, 'Gezegen temalı hedef istasyonları', 'Her hedef bir "gezegen" olarak kurgulanır, sporcu sırayla gezegenleri vurarak uzay yolculuğunu tamamlar.', '["4-5 hedefi farklı \"gezegen\" olarak etiketleme","Roket kalkışı temalı kısa bir giriş yapma","Her gezegende 2 ok hakkı ile ilerleme","Son gezegene (Dünya''ya dönüş) ulaşanları \"astronot\" ilan etme"]', '["Tema anlatımı kısa tutulmalı, asıl odak atış tekrarında kalmalı"]', 'Sistem', 1784413500670, 1784413500670),
('oyun-05', 'oyun', 'Hayvanları Kurtar', 'baslangic', '["kucukler","minikler"]', 25, 'Hayvan figürlü/resimli hedef kartları', 'Hedeflere yerleştirilen hayvan kartları isabetli atışla "kurtarılır" ve bir kutuya toplanır.', '["Hedefe 6-8 hayvan kartı yerleştirme","Her isabetli atışta kartı hedeften alıp \"kurtarılanlar\" kutusuna koyma","Tüm hayvanlar kurtarılana kadar sırayla devam etme","Kurtarılan hayvan sayısını kutlama"]', '["Kartlar hedefe güvenli şekilde (ok ucu zarar vermeyecek) tutturulmalı"]', 'Sistem', 1784413500670, 1784413500670),
('oyun-06', 'oyun', 'Kale Savunması', 'orta', '["kucukler","minikler","yildizlar"]', 30, 'Kale/kule maketi veya çizimi, hedef', 'Sporcular sırayla "kaleyi" savunmak için hedefteki "istilacıları" (işaretli bölgeler) vurur, takım halinde puan biriktirir.', '["Hedefi kale temalı bölgelere ayırma","Takım halinde sırayla atış yapıp puan biriktirme","Belirli bir puana ulaşınca \"kale savunuldu\" ilan etme","Takımlar arasında kısa bir kutlama/rozet töreni"]', '["Takım içi sıralama net olmalı, herkesin atış hakkı eşit dağıtılmalı"]', 'Sistem', 1784413500670, 1784413500670),
('oyun-07', 'oyun', 'Adım Adım Şampiyon (Seviye Atlama)', 'baslangic', '["kucukler","minikler"]', 35, 'Seviye kartları/rozetleri, hedef', 'Sporcu her seviyede belirli bir isabet sayısına ulaşınca bir üst seviyeye (bronz→gümüş→altın) geçer.', '["3 seviye belirleme (ör. bronz: 3/6 isabet, gümüş: 4/6, altın: 5/6)","Sporcu bronz seviyeden başlar, her seride seviyesini test eder","Seviye atlayan sporcuya kart/rozet verme","Ders sonunda herkesin ulaştığı seviyeyi pano üzerinde gösterme"]', '["Seviye eşikleri her sporcunun mevcut düzeyine göre esnetilebilir, imkansız hedef konulmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('oyun-08', 'oyun', 'Define Haritası', 'baslangic', '["kucukler","minikler"]', 30, 'Çizili define haritası, hedef istasyonları', 'Büyük bir kağıda çizilmiş define haritasında her isabetli atış sporcuyu bir sonraki işarete taşır.', '["Basit bir define haritası çizip 5-6 durak belirleme","Her durakta 2 ok hakkı ile ilerleme kuralını anlatma","Sporcuları sırayla haritada ilerletme","Define noktasına ulaşanları küçük bir ödülle kutlama"]', '["Harita görsel olarak eğlenceli ama basit tutulmalı, karışıklığa yol açmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('oyun-09', 'oyun', 'Ejderha Avcısı', 'baslangic', '["kucukler","minikler"]', 30, 'Ejderha figürlü büyük hedef', 'Büyük bir "ejderha" hedefinin farklı bölgelerine (kanat, kuyruk, göz) isabet ettikçe puan artar, sporcular kahraman unvanı kazanır.', '["Hedefi ejderha bölgelerine göre puanlandırma (göz=yüksek puan, kuyruk=düşük puan gibi)","Her sporcuya 3 ok hakkı tanıma","Toplam puanına göre \"Ejderha Avcısı\" unvanları dağıtma (Çırak/Usta/Kahraman)","İsteyen sporculara ikinci deneme hakkı verme"]', '["Unvan sistemi motive edici olmalı, düşük puan alanlar küçümsenmemeli"]', 'Sistem', 1784413500670, 1784413500670),
('oyun-10', 'oyun', 'Yıldız Toplama Oyunu', 'baslangic', '["kucukler","minikler"]', 25, 'Yıldız etiketli hedef alanları, biriktirme kartı', 'Her isabetli atış bir "yıldız" kazandırır, sporcular kendi biriktirme kartlarına yıldız toplar.', '["Her sporcuya küçük bir yıldız biriktirme kartı verme","Her isabetli atışta karta bir yıldız çıkartması/işareti ekleme","Belirlenen yıldız sayısına ulaşanları duyurma","Kartları ders sonunda sporcularla paylaşma (bir sonraki derse getirmeleri için)"]', '["Kartın devamlılığı (birkaç ders boyunca biriktirme) motivasyonu uzun vadede artırır"]', 'Sistem', 1784413500670, 1784413500670),
('yetiskin-01', 'teknik', 'Yetişkin Başlangıç — Kas Hafızası Oluşturma', 'baslangic', '["buyukler"]', 40, 'Lastik bant, yay', 'Yeni başlayan yetişkinlerde doğru hareket kalıbını erken aşamada kas hafızasına yerleştirmeyi hedefler.', '["Temel duruş-çekiş-salıverme dizisini yavaş tempoda 15 tekrar","Lastik bantla izole kas çalışması (sırt/omuz)","Yayla 4 seri kontrollü atış, her arada geri bildirim","Ders sonunda \"ev ödevi\" olarak günlük 10 dakikalık kuru çekiş önerisi"]', '["Yetişkinlerde öğrenme hızı bireysel farklılık gösterir, karşılaştırma yapılmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('yetiskin-02', 'teknik', 'Dayanıklılık ve Tekrar Antrenmanı', 'orta', '["buyukler"]', 45, 'Yay, ok, kronometre', 'Uzun seri sayılarında form bozulmadan devam edebilme kapasitesini geliştirir.', '["Isınma sonrası 6 seri (36-72 ok) planlı atış programı","Her 2 seride bir kısa (2dk) dinlenme","Son serilerde form bozulması gözlenirse not alma","Kapanışta yorgunluk anındaki teknik farkını sporcuyla paylaşma"]', '["Ağrı/sakatlık belirtisi varsa antrenman derhal durdurulmalı","Dayanıklılık kazanımı haftalar sürer, tek derste zorlama yapılmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('yetiskin-03', 'teknik', 'Yarışma Stresi Simülasyonu', 'ileri', '["buyukler","yildizlar"]', 35, 'Hedef, izleyici/gözlemci (varsa), skor kağıdı', 'Gerçek yarışma baskısını (izlenme, resmi skor, tek şans hissi) küçük ölçekte simüle ederek mental dayanıklılık kazandırır.', '["Sporcuları \"sadece 1 deneme hakkı var\" kuralıyla bilgilendirme","Resmi skor kağıdıyla 3 seri attırma, mümkünse izleyici önünde","Sonuçları objektif şekilde paylaşma","Baskı altında hissettiklerini kısaca konuşma turu"]', '["Amaç kaygı yaratmak değil, tanıdık bir baskı ortamında rahatlamayı öğretmek"]', 'Sistem', 1784413500670, 1784413500670),
('yetiskin-04', 'teknik', 'İleri Seviye Mental Antrenman ve Odaklanma', 'ileri', '["buyukler"]', 30, 'Sessiz bir alan, yay', 'Görselleştirme ve nefes teknikleriyle atış öncesi zihinsel hazırlığı geliştirir.', '["Kısa bir görselleştirme egzersiziyle (mükemmel atışı zihinde canlandırma) başlama","Her atıştan önce 3 saniyelik nefes-odaklanma rutini uygulatma","5 seri atışla rutini pekiştirme","Zihinsel rutinin skor tutarlılığına etkisini birlikte değerlendirme"]', '["Mental teknikler kişiye göre farklı işler, tek bir yöntem herkese dayatılmamalı"]', 'Sistem', 1784413500670, 1784413500670),
('yetiskin-05', 'teknik', 'Fiziksel Kondisyon ve Okçuluk Kas Grupları', 'orta', '["buyukler"]', 35, 'Lastik bant, hafif ağırlıklar (opsiyonel)', 'Okçuluk için kritik kas gruplarını (sırt, karın, omuz stabilizatörleri) güçlendiren destekleyici antrenman.', '["Genel ısınma (5dk)","Sırt/omuz için lastik bant egzersizleri (3 set x 12 tekrar)","Karın/core stabilizasyon egzersizleri (plank vb.)","Kapanışta yayla hafif teknik pekiştirme (2 seri)"]', '["Egzersizler okçuluk formunu bozmayacak, tamamlayıcı nitelikte olmalı, ağır kuvvet antrenmanına dönüşmemeli"]', 'Sistem', 1784413500670, 1784413500670),
('yetiskin-06', 'teknik', 'İleri Form Düzeltme ve Video Analiz Seansı', 'ileri', '["buyukler","yildizlar"]', 40, 'Telefon/kamera, yay, hedef', 'Sporcunun atışı kaydedilip birlikte izlenerek ince teknik detaylar (dirsek açısı, omuz hizası) üzerinde çalışılır.', '["3-5 okluk bir seri kaydetme (uygulamadaki Video Analiz sekmesi kullanılabilir)","Kaydı birlikte izleyip 1-2 gelişim noktası belirleme","Belirlenen noktaya odaklanarak 3 seri daha atış","Öncesi/sonrası karşılaştırmalı kısa değerlendirme"]', '["Video üzerinden eleştiri yapıcı ve spesifik olmalı, genel/belirsiz yorumlardan kaçınılmalı"]', 'Sistem', 1784413500670, 1784413500670),
('yildiz-01', 'eglence', 'Yıldızlar Takım Uyumu Antrenmanı', 'baslangic', '["yildizlar"]', 35, 'Hedef, takım renkleri/bantları', 'Yıldız grubunun kendi içinde takım kimliği ve dayanışma kazanmasını hedefleyen, puanın takım toplamıyla ölçüldüğü bir antrenman.', '["Grubu 2 dengeli takıma ayırma, takım isimleri belirletme","Takım içi rotasyonla 4 seri atış, toplam puanı takip etme","Aralarda takım kaptanının kısa bir motivasyon konuşması yapmasına izin verme","Sonuçları duyurup her iki takımı da tebrik etme"]', '["Kazanan-kaybeden ayrımından çok \"birlikte gelişim\" vurgusu yapılmalı"]', 'Sistem', 1784413500670, 1784413500670),
('yildiz-02', 'teknik', 'Rekabetçi Set Sistemi Alıştırması', 'orta', '["yildizlar"]', 40, 'Hedef, skor kağıdı, düello modu (uygulama üzerinden opsiyonel)', 'Yıldız sporcularını World Archery set sistemine (uygulamadaki Düello Modu ile de desteklenebilir) alıştıran ikili eşleşme dersi.', '["Sporcuları seviyeye göre ikili eşleştirme","Set sistemi kurallarını (her seri kazananı 2 set puanı alır) hatırlatma","3-4 maç oynatma, sonuçları kaydetme","Genel gözlemleri (baskı altında performans) paylaşma"]', '["Eşleşmeler adil olmalı, sürekli aynı sporcunun kaybetmesi motivasyonu düşürebilir"]', 'Sistem', 1784413500670, 1784413500670),
('yildiz-03', 'teknik', 'Bireysel Gelişim Takibi Dersi', 'orta', '["yildizlar"]', 30, 'Sporcu geçmiş skor kayıtları (uygulama üzerinden)', 'Her sporcuyla kısa bireysel görüşme yapılıp geçmiş performansı (uygulamadaki Gelişim grafiği) birlikte incelenir, hedef belirlenir.', '["Her sporcuyla 3-5 dakikalık bireysel görüşme","Gelişim grafiğini birlikte inceleyip güçlü/gelişime açık yönleri konuşma","Kısa vadeli (1 haftalık) somut bir hedef belirleme (uygulamadaki Kişisel Hedef özelliği kullanılabilir)","Kalan sürede serbest atış practice"]', '["Bireysel görüşme sırasında diğer sporcular gözetimsiz kalmamalı, kısa aralıklarla yapılmalı"]', 'Sistem', 1784413500670, 1784413500670),
('yildiz-04', 'teknik', 'Karma Beceri Antrenmanı', 'orta', '["yildizlar"]', 40, 'Hedef, farklı mesafe işaretleri, skor kağıdı', 'Teknik, dayanıklılık ve mental odaklanmayı tek derste birleştiren, Yıldız grubunun genel seviyesine uygun kapsamlı antrenman.', '["10dk teknik ısınma (duruş/anchor tekrarı)","15dk değişken mesafeli seri atışları","10dk zamana karşı mini yarışma","5dk kapanış ve gün değerlendirmesi"]', '["Dört bölüm arasında geçişler net duyurulmalı, sporcular hangi aşamada olduklarını bilmeli"]', 'Sistem', 1784413500670, 1784413500670),
('yildiz-05', 'eglence', 'Hedef Koyma ve Motivasyon Atölyesi', 'baslangic', '["yildizlar"]', 25, 'Kağıt, kalem, sporcu geçmiş verileri', 'Sporcuların kısa/orta vadeli kişisel hedeflerini kendi yazdığı, atışla birleştirilen motivasyon odaklı bir ders.', '["Her sporcudan bu ay için 1 hedef yazmasını isteme (ör. \"ortalamamı 5 puan artırmak\")","Hedefleri kısaca paylaşma (isteyenler için)","Hedefe yönelik 3 seri odaklı atış","Kapanışta hedef kağıtlarını saklamaları için sporculara verme"]', '["Hedefler gerçekçi ve ölçülebilir olmalı, eğitmen gerekirse yönlendirme yapmalı"]', 'Sistem', 1784413500670, 1784413500670),
('yildiz-06', 'eglence', 'Mini Lig Hazırlık Antrenmanı', 'ileri', '["yildizlar"]', 45, 'Hedef, skor kağıdı, uygulamadaki Turnuva/Eleme Ağacı modülü (opsiyonel)', 'Yaklaşan bir kulüp içi turnuvaya hazırlık amacıyla, gerçek eleme formatını (uygulamadaki Eleme Ağacı özelliğiyle de desteklenebilir) deneyimleten ders.', '["Sporcuları sıralama turu ile seviyelendirme (klasman puanına göre de yapılabilir)","Eleme ağacı formatında eşleştirme","1-2 tur maç oynatma","Yarı final/final heyecanını yaşatacak şekilde son maçı öne çıkarma"]', '["Elenen sporcuların da izleyici olarak derse dahil kalması sağlanmalı, moral bozulmamalı"]', 'Sistem', 1784413500670, 1784413500670);
