ALTER TABLE ders_icerikleri ADD COLUMN kategori TEXT;
ALTER TABLE ders_icerikleri ADD COLUMN kazanim TEXT;

ALTER TABLE members ADD COLUMN boy INTEGER;         -- cm
ALTER TABLE members ADD COLUMN kilo REAL;           -- kg
ALTER TABLE members ADD COLUMN saglikNotu TEXT;     -- hastalik/ozel durum notu, genelNot'tan ayri ve net etiketli

-- 30 hazir ders havuzu (id: havuz_01..havuz_30) — milo_ders_havuzu_30.md'den scripts/gen-milo-ders-havuzu.cjs
-- ile otomatik uretildi (elle transkripsiyon hatasi riskini onlemek icin).
INSERT INTO ders_icerikleri (id, tip, baslik, seviye, kategori, kazanim, gruplar_json, aciklama, adimlar_json, dikkat_json, olusturan, olusturulma, guncelleme) VALUES
  ('havuz_01', 'hareket', 'Doğru Duruş ve Nefes', 'baslangic', 'Temel Cimnastik', 'Vücut farkındalığı, doğru postür.', '["genel"]', 'Ayaklar omuz genişliğinde, sırt dik, karın hafif içeride. Burundan al, ağızdan ver. Tüm hareketlerin temeli.', '[]', '[]', 'sistem', 1784663495939, 1784663495939),
  ('havuz_02', 'hareket', 'Vücut Pozisyonları (Tuck-Pike-Straddle)', 'baslangic', 'Temel Cimnastik', 'Temel şekilleri tanıma, ileri hareketlere hazırlık.', '["genel"]', 'Toplanma (tuck), bükülü (pike), açık bacak (straddle) pozisyonlarını otururken öğren. Cimnastiğin "alfabesi".', '[]', '[]', 'sistem', 1784663495940, 1784663495940),
  ('havuz_03', 'hareket', 'Yön ve Boşluk Farkındalığı', 'baslangic', 'Temel Cimnastik', 'Mekansal farkındalık (proprioception).', '["genel"]', 'İleri-geri-yan, yukarı-aşağı komutlarıyla mat üstünde hareket. Baş aşağı-baş yukarı kavramı. Küçük yaşta mekan algısı.', '[]', '[]', 'sistem', 1784663495941, 1784663495941),
  ('havuz_04', 'hareket', 'Eklem Turları Isınması', 'baslangic', 'Isınma', 'Isınma alışkanlığı, eklem hareketliliği.', '["genel"]', 'Boyun, omuz, bilek, kalça, diz, ayak bileği sırayla 8''er tur. Sakatlığı önler.', '[]', '[]', 'sistem', 1784663495942, 1784663495942),
  ('havuz_05', 'hareket', 'Hayvan Yürüyüşleri (Ayı-Yengeç-Tavşan)', 'baslangic', 'Isınma', 'Tüm vücut koordinasyonu, kol-omuz gücü.', '["genel"]', 'Ayı (eller-ayaklar yerde), yengeç (sırt üstü karın yukarı), tavşan sıçrayışı. Eğlenceli ısınma + güç.', '[]', '[]', 'sistem', 1784663495943, 1784663495943),
  ('havuz_06', 'hareket', 'Kalp Atışı Oyunu (Kardiyo)', 'baslangic', 'Kondisyon', 'Dayanıklılık, ritim.', '["genel"]', 'Yerinde koşu, jumping jack, yüksek diz sırayla — müzikle. Kondisyonu artırır, enerjiyi toplar.', '[]', '[]', 'sistem', 1784663495944, 1784663495944),
  ('havuz_07', 'hareket', 'Tek Ayak Duruşu (Flamingo)', 'baslangic', 'Denge', 'Denge kontrolü, gövde stabilizasyonu.', '["genel"]', 'Tek ayak üstünde dur, diğer dizi öne çek, kollar yana. Önce 5 sn, sonra 10 sn. İki ayakla da.', '[]', '[]', 'sistem', 1784663495945, 1784663495945),
  ('havuz_08', 'hareket', 'Denge Çizgisi Yürüyüşü', 'baslangic', 'Denge', 'Çizgi dengesi, konsantrasyon.', '["genel"]', 'Yerdeki çizgi/alçak denge aleti üstünde topuk-parmak yürü, kollar yana açık. Geri ve yan yürüyüş ile zorlaştır.', '[]', '[]', 'sistem', 1784663495946, 1784663495946),
  ('havuz_09', 'hareket', 'Denge Aletinde Temel Hareketler', 'gelisen', 'Denge', 'Alette denge ve özgüven.', '["genel"]', 'Alçak denge aletinde yürüme, dönme, diz kaldırma, kol açma. Yükseklik korkusunu nazikçe aşma.', '[]', '[]', 'sistem', 1784663495947, 1784663495947),
  ('havuz_10', 'hareket', 'Otur-Uzan (Öne Esneme)', 'baslangic', 'Esneklik', 'Arka bacak (hamstring) esnekliği, sabır.', '["genel"]', 'Bacaklar düz öne uzalı, ellerle ayak parmaklarına uzan. Zorlamadan, nefes vererek.', '[]', '[]', 'sistem', 1784663495948, 1784663495948),
  ('havuz_11', 'hareket', 'Kelebek Oturuşu', 'baslangic', 'Esneklik', 'Kalça esnekliği.', '["genel"]', 'Ayak tabanlarını birleştir, dizleri nazikçe yere indir. Temel kalça açıcı.', '[]', '[]', 'sistem', 1784663495949, 1784663495949),
  ('havuz_12', 'hareket', 'Köprü (Bridge)', 'gelisen', 'Esneklik', 'Sırt esnekliği, geri takla köprüsü temeli.', '["genel"]', 'Sırt üstü yat, elleri kulak yanına koy, itip kalçayı kaldır. Sırt-omuz esnekliği + kol gücü.', '[]', '[]', 'sistem', 1784663495950, 1784663495950),
  ('havuz_13', 'hareket', 'Split Çalışması', 'ileri', 'Esneklik', 'İleri seviye bacak esnekliği.', '["genel"]', 'Öne split, yavaşça alçal, zorlamadan. Aylara yayılan sabır işi.', '[]', '[]', 'sistem', 1784663495951, 1784663495951),
  ('havuz_14', 'hareket', 'Karın-Sırt Güçlendirme (Süpermen-Tekne)', 'baslangic', 'Güç', 'Karın-sırt (core) gücü.', '["genel"]', 'Süpermen (yüzükoyun kol-bacak kaldır), tekne (sırt üstü V pozisyonu). Gövde gücü çekirdeği.', '[]', '[]', 'sistem', 1784663495952, 1784663495952),
  ('havuz_15', 'hareket', 'Plank ve Şınav Hazırlık', 'gelisen', 'Güç', 'Üst vücut ve core gücü.', '["genel"]', 'Plank duruşu (düz vücut), diz üstü şınav. Kol ve gövde gücü — amut ve takla için şart.', '[]', '[]', 'sistem', 1784663495953, 1784663495953),
  ('havuz_16', 'hareket', 'Kutu Sıçraması (Patlayıcı Güç)', 'gelisen', 'Güç', 'Alt vücut gücü, sıçrama kontrolü.', '["genel"]', 'Alçak kutuya/basamağa çift ayak sıçra-in, yumuşak iniş. Patlayıcı bacak gücü.', '[]', '[]', 'sistem', 1784663495954, 1784663495954),
  ('havuz_17', 'hareket', 'Yuvarlanma Hazırlık (Salıncak-Yumurta)', 'baslangic', 'Yuvarlanma', 'Yuvarlanma hissi, sırt koruma.', '["genel"]', 'Tuck pozisyonda öne-arkaya salınım, "yumurta" gibi yuvarlan. Takla öncesi hazırlık.', '[]', '[]', 'sistem', 1784663495955, 1784663495955),
  ('havuz_18', 'hareket', 'Öne Takla (Forward Roll)', 'gelisen', 'Takla', 'Öne takla — temel hareket.', '["genel"]', 'Çömel, elleri yere koy, çeneyi göğse çek, sırtı yuvarlayarak öne takla. Baş DEĞİL sırt değer. Mat + gözetim.', '[]', '[]', 'sistem', 1784663495956, 1784663495956),
  ('havuz_19', 'hareket', 'Geriye Takla (Backward Roll)', 'gelisen', 'Takla', 'Geriye takla, mekansal kontrol.', '["genel"]', 'Sırt üstü, dizleri çek, elleri omuz yanından yere bas, geriye yuvarlan. İtme gücü şart. Gözetim.', '[]', '[]', 'sistem', 1784663495957, 1784663495957),
  ('havuz_20', 'hareket', 'Takla Kombinasyonları', 'ileri', 'Takla', 'Hareket geçişi, akıcılık.', '["genel"]', 'Öne + geriye taklayı arka arkaya akıcı yap. Sadece ikisi de sağlamsa.', '[]', '[]', 'sistem', 1784663495958, 1784663495958),
  ('havuz_21', 'hareket', 'Amut Hazırlık (Duvar Desteği)', 'gelisen', 'Amut', 'Amut için kol gücü, baş aşağı duruşa alışma.', '["genel"]', 'Duvara sırtı dönük, elleri yere, ayakları duvardan yukarı yürüt. Kollar düz, karın sıkı.', '[]', '[]', 'sistem', 1784663495959, 1784663495959),
  ('havuz_22', 'hareket', 'Amutta Durma (Handstand)', 'ileri', 'Amut', 'Amutta denge — gurur hareketi.', '["genel"]', 'Duvar desteği ya da gözetimde amuda kalk, dengeyi bul. Vücut tek çizgi. Önce 3 sn, sonra artır.', '[]', '[]', 'sistem', 1784663495960, 1784663495960),
  ('havuz_23', 'hareket', 'Amuttan Takla ile İniş', 'ileri', 'Amut', 'Hareket birleştirme, kontrol.', '["genel"]', 'Amuda kalk, kontrollü öne takla ile in. Amut ve öne takla sağlamsa.', '[]', '[]', 'sistem', 1784663495961, 1784663495961),
  ('havuz_24', 'hareket', 'Sıçrama ve Sessiz İniş', 'baslangic', 'Sıçrama', 'Güvenli iniş tekniği.', '["genel"]', 'Yerinde sıçra, dizleri bükerek yumuşak "sessiz" in. Doğru iniş tüm cimnastikte sakatlığı önler.', '[]', '[]', 'sistem', 1784663495962, 1784663495962),
  ('havuz_25', 'hareket', 'Yarım Dönüş Sıçrama', 'gelisen', 'Sıçrama', 'Havada yön kontrolü, denge.', '["genel"]', 'Sıçrarken havada yarım dön (180°), dengeli in. Sonra tam dönüşe (360°) ilerle.', '[]', '[]', 'sistem', 1784663495963, 1784663495963),
  ('havuz_26', 'hareket', 'Kartwheel (Yan Takla)', 'ileri', 'Dönüş', 'Tam kartwheel, yön koordinasyonu.', '["genel"]', 'Çizgi üstünde el-el-ayak-ayak yan geçiş. Önce yavaş adım adım, sonra akıcı tek hareket. Bacaklar açık, kollar düz.', '[]', '[]', 'sistem', 1784663495964, 1784663495964),
  ('havuz_27', 'hareket', 'Engel Parkuru (Obstacle Course)', 'baslangic', 'Oyun-Temelli', 'Çeviklik, takım çalışması, sıra bekleme.', '["genel"]', 'Mat altından geçme, tünel, koni atlama, denge çizgisi istasyonları. Sırayla geç. Takım ruhu + çok yönlü beceri.', '[]', '[]', 'sistem', 1784663495965, 1784663495965),
  ('havuz_28', 'hareket', 'Heykel / Müzik Durunca (Balance Freeze)', 'baslangic', 'Oyun-Temelli', 'Dinleme, ani denge, eğlenerek öğrenme.', '["genel"]', 'Müzik çalarken hareket, durunca bir denge pozisyonunda "donma". Renk/şekil komutlarıyla zenginleştir.', '[]', '[]', 'sistem', 1784663495966, 1784663495966),
  ('havuz_29', 'hareket', 'Hayvan Taklidi Zinciri (Hareket Tahmini)', 'gelisen', 'Oyun-Temelli', 'Yaratıcılık, hareket dizisi kurma.', '["genel"]', 'Öğrenci hayvan hareketleri dizisi kurar, diğerleri tahmin eder. Hız-ritim-vücut hareketi düşünmeyi öğretir.', '[]', '[]', 'sistem', 1784663495967, 1784663495967),
  ('havuz_30', 'hareket', 'Mini Gösteri (Serbest Seri)', 'gelisen', 'Koordinasyon', 'Özgüven, öğrendiklerini sergileme, akıcılık.', '["genel"]', 'Öğrenci öğrendiği hareketlerden (örn. sıçrama → öne takla → denge duruşu) kendi kısa serisini kurar ve sunar.', '[]', '[]', 'sistem', 1784663495968, 1784663495968);
